# Generated by Django 4.2 on 2023-05-31 22:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_limite_venta', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('lote', models.CharField(blank=True, max_length=30, null=True)),
                ('valor', models.PositiveBigIntegerField()),
                ('producto_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.productostock')),
            ],
            options={
                'verbose_name': 'Producto Batch',
                'verbose_name_plural': 'Productos Batch',
            },
        ),
    ]
