# Generated by Django 4.2 on 2023-04-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='descrpcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
