# Generated by Django 4.2 on 2023-04-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_movimientostock_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientostock',
            old_name='estado',
            new_name='tipo_movimiento',
        ),
    ]
