# Generated by Django 4.2 on 2023-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_rename_estado_movimientostock_tipo_movimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientostock',
            old_name='descrpcion',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='productolote',
            name='fecha_recepcion',
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='fecha_limite_venta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productolote',
            name='fecha_limite_venta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productolote',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
