# Generated by Django 4.2 on 2023-04-24 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_rename_descrpcion_movimientostock_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
