# Generated by Django 4.2 on 2023-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_alter_producto_stock_alter_productostock_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
