# Generated by Django 4.2 on 2023-04-25 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_alter_movimientostock_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='fecha_limite_venta',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
