# Generated by Django 4.2 on 2023-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_alter_movimientostock_fecha_limite_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='valor',
            field=models.PositiveBigIntegerField(),
        ),
    ]
